name: Publish Release

on:
  push:
    branches:
      - release
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log Level'
        required: false
        default: 'warning'

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "contains(github.event.commits[0].message, '[build]')"
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Plugin
        run: ./gradlew build --stacktrace

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CrazyCrates-JAR
          path: build/libs/*.jar

      - name: Publish to Modrinth and Hangar
        if: env.HANGAR_KEY != '' && env.MODRINTH_TOKEN != ''
        env:
          HANGAR_KEY: ${{ secrets.HANGAR_KEY }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          COMMIT_MESSAGE: ${{ join(github.event.commits.*.message, '<br>* ') }}
        run: ./gradlew modrinth publishAllPublicationsToHangar --stacktrace
