name: Build Crazy Crates Plugin
on:
  push:
    branches:
      - main  # Change this to your preferred branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          check-latest: true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build JAR
        run: ./gradlew assemble

      - name: Upload JAR as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: crazy-crates-plugin
          path: build/libs/*.jar

